[package]
name = "Lyrico"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "lyrico_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lofty = "0.24.0"
walkdir = "2.5.0"
base64 = "0.22.1"
mime_guess = "2.0.5"
tauri-plugin-dialog = "2.7.1"
image = { version = "0.25.8", default-features = false, features = ["jpeg", "png", "gif", "webp"] }
rusqlite = { version = "0.40.1", features = ["bundled"] }
rayon = "1.11.0"
ebur128 = "0.1.10"
symphonia = { version = "0.6.0", features = ["all"] }
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }
rquickjs = "0.12.0"
reqwest = { version = "0.13.2", default-features = false, features = ["blocking", "rustls", "gzip", "brotli", "deflate"] }
md-5 = "0.10.6"
aes = "0.8.4"
ecb = { version = "0.1.2", features = ["alloc", "block-padding"] }
flate2 = "1.1.9"
cipher = { version = "0.4.4", features = ["alloc", "block-padding"] }
quick-xml = "0.41.0"
regex = "1.12.2"
roxmltree = { version = "0.21.1", default-features = false, features = ["std"] }
ferrous-opencc = "0.3.1"


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
